version: '3'

services:
  training_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - model_data:/app/models
    
volumes:
  model_data: